#!/bin/sh
set -e
echo ">>>>>> Installing JRuby"
#install jruby
curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/use-ruby
RUBY_VERSION=jruby-1.6.6 source ./use-ruby
#echo ruby version
echo ">>>>>> Echoing Ruby Version"
ruby -v

echo ">>>>>> Installing Bundler"
#install bundler
gem install rake
gem install bundler

#install all gems
echo ">>>>>> Installing all Gems"
# bundle check || bundle install --deployment --local --without development
bundle install --deployment --local --without development

echo ">>>>>> Creating War"
#create war
warble war

set +e