#!/bin/sh
set -e
echo ">>>>>> Installing JRuby"
#install jruby
curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/use-ruby
#RUBY_VERSION=jruby-1.6.6 source ./use-ruby
RUBY_VERSION=1.9.3-p125 source ./use-ruby
#echo ruby version
echo ">>>>>> Echoing Ruby Version"
ruby -v

echo ">>>>>> Installing Bundler"
#install bundler
gem install rake -i ./vendor/rake
export PATH=./vendor/rake/bin:$PATH

gem install bundler --no-ri --no-rdoc

#install all gems
echo ">>>>>> Installing all Gems"
# bundle check || bundle install --deployment --local --without development
bundle install --deployment --local 

echo ">>>>>> Creating War"
#create war
bundle exec warble war

set +e